/* Autor: Prof. Dr. Norman Lahme-Hütig (FH Münster) */

import './components/app/app.ts';
import './components/main/stonks.ts';
import './components/news/FinnHubMarketNews.ts';
import './components/forgotPassword/forgotPassword.js';
import './components/forgotPassword/resetPassword.js';
import './components/sign-in/sign-in.ts';
import './components/sign-out/sign-out.ts';
import './components/sign-up/sign-up.ts';
import './components/sign-up/activation.ts';
import './components/widgets/notification/notification.ts';
import './components/trading/portfolio/portfolio.js';
import './components/trading/market/market.js';
import './components/trading/portfolio/portfolio.js';
import './components/transaction-history/transaction-history.ts';
import './components/user-profile/user-profile.ts';
import './components/user-profile/avatar/avatar.ts';
import './components/user-profile/constraints/constraints.ts';
import './components/user-profile/details/details.ts';
import './components/user-profile/password/password.ts';
import './components/widgets/loader/loader.ts';
import './components/widgets/notification/notification.ts';
import './components/widgets/page-navigator/page-navigator.ts';
import './components/trading/trading-widgets/notificationcomponent.ts';
//Alex L:
import './components/trading/trading-details/trading-details.js';
import './components/main/main.ts';
import './components/header/header.ts';
import './components/leaderboard/leaderboard.ts';
import './components/friends/friends.ts';
import './components/widgets/rating/my-rating.js';
import './components/bigstocksgobrrr/minesweeper.js';
